import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar/Navbar";
import { ActivePageProvider } from "@/hook/ActivePage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ActivePageProvider>
          <div className="app_wrapper flex justify-center w-full box-border m-0 p-0">
            <header className="relative flex-shrink-0 flex-grow items-end flex flex-col">
              <Navbar />
            </header>
            <main className="w-[1050px]">{children}</main>
          </div>
        </ActivePageProvider>
      </body>
    </html>
  );
}
